### PR TITLE
Update to 2022.2

### PR DESCRIPTION
**Pull request by jacquesg**
Released 21 December 2022

### CODE REVIEW

**Comment by sabas** [comment]
Hi, I already uploaded 2022.1, Could you please clarify?

**Comment by jacquesg** [comment]
Apologies, updated to `2022.2`.

**Comment by sabas** [comment]
Thanks, can you please bump the edition also in datapackage.json?

**Comment by jacquesg** [comment]
> Thanks, can you please bump the edition also in datapackage.json?

Done.

**Comment by sabas** [comment]
Perfect thanks :)

**Pull request merged**
