### PR TITLE
Update data to 2014.2 edition

### PR DESCRIPTION
**Pull request by sabas**
I updated data with the edition 2014.2 released on December 29th with the same process, bumping version to 2014.2.0 .
I tweaked also the readme.

### CODE REVIEW

**Comment by sabas** [comment]
Damn it's so cool comparing versions via Git.

**Comment by rgrp** [comment]
@sabas +1 - you may also be interested in http://blog.okfn.org/2013/07/02/git-and-github-for-data/ and http://okfnlabs.org/blog/2013/08/08/diffing-and-patching-data.html

**Comment by rgrp** [comment]
@sxren are you up for reviewing ...

**Comment by sxren** [comment]
@sabas @rgrp the datapackage.json is [valid](http://data.okfn.org/tools/validate?url=https%3A%2F%2Fraw.githubusercontent.com%2Fsabas%2Fun-locode%2Fcaf4b17b34e0a2c9c84b5a6c80f71629d171f9b0%2Fdatapackage.json). i don't see any issues in the [data package viewer](http://data.okfn.org/tools/view?url=https%3A%2F%2Fraw.githubusercontent.com%2Fsabas%2Fun-locode%2Fcaf4b17b34e0a2c9c84b5a6c80f71629d171f9b0%2Fdatapackage.json) or the diffs that should hold up the commit. :+1:

**Comment by rgrp** [comment]
@sxren do you want the privilege :-0 of merging :-)

**Comment by sabas** [comment]
Wait a sec if possible, I noticed that the readme need a fix

**Comment by sabas** [comment]
Done

**Comment by sxren** [comment]
@rgrp i did something wrong. this commit should be credited to @sabas.

**Comment by sabas** [comment]
@sxren it's ok the commit, you performed the merge operation, see the history https://github.com/datasets/un-locode/commits/master 

Thanks!

**Comment by sxren** [comment]
@sabas ah! i see! thanks!

**Pull request merged**
