### PR TITLE
Minor fixes

### PR DESCRIPTION
**Pull request by gradedSystem**
## Changes made:

- Fixed the repository 
- Cleaned up some files
- Updated the links in `README.md`
- Added `gitignore` file
- Updated the `data/` folder

cc @anuveyatsu

### CODE REVIEW

**Comment by sabas** [comment]
Hi, can I review the changes tomorrow? Thanks

**Comment by gradedSystem** [comment]
sure you can review @sabas

**Comment by cristan** [comment]
I'll be the bearer of bad news: I don't think there's any chance this will be merged.

The thing is: this project isn't the actual source of the UN/LOCODE dataset: it's only a way to take the official distribution and package it in a much more convenient way. Maybe this can be made a little bit clearer in the README.

Your changes both change the form of the data (the ordering of the countries for example), as well as its contents. The form could be changed as part of this project, but any content has to go though a committee at UNECE. sabas is in contact with them though, so he might be able to make some of these a reality. 

Anyway, let's look at your changes:

- Some countries have their names changes, like "United States of America (the)" to "United States". That is already a major, major change which has to go through the committee.
- Countries are ordered alphabetically. If you want this, you should change the python who generate this file, so these are generated alphabetically.
- Countries removed, like `XZ,Installations in International Waters`. This is a big no no. There are [tons](https://unlocode.info/country/XZ) of un/locodes there.
- function-classifiers.csv are changed. I don't like this change at all. "_number_ Specifies that the location is a" doesn't say anything at all. Also, "Value reserved for" implies that this isn't used, but it is. Like AEHIL has the status 7, like 23 others.
- status-indicators.csv changed. One of the changes is that you removed AM. This is bad. There are 650 unlocodes which have this status, like AESZE

I'm sorry for the effort you put into this, but I don't see these changes ending up in this repo like this at all.

**Comment by anuveyatsu** [comment]
hi @cristan thank you for pointing this out! Please note that there is another pull request here with changes to the python code #29 - could you please take a look at it and leave your comments there? I believe that the changes in the data content is a result of those python scripts, i.e., if a country name has changed it must be an issue in the upstream. However, we need to confirm it first. cc @gradedSystem

**Comment by gradedSystem** [comment]
@sabas @cristan @anuveyatsu going to close this pull request going to look into fixing the code with suggested changes

**Pull request closed without merging**
