### PR TITLE
Update to version 2015-2

### PR DESCRIPTION
**Pull request by sabas**
Update to the second release of 2015, with 2866 changes reported.
See also http://www.unece.org/fileadmin/DAM/cefact/locode/2015-2_UNLOCODE_SecretariatNotes.pdf

### CODE REVIEW

**Comment by rgrp** [comment]
@sabas this is great - thank-you.

Before we merge: do you have any summary of the changes and you done a quick check to make sure the diff makes sense (it is too big to preview here on github).

**Comment by sabas** [comment]
@rgrp I did the usual conversion steps so I didn't actually check before pushing. Here's a quick daff I rendered. https://dl.dropboxusercontent.com/u/12087738/locode2015daff.html
Seems all ok (for example the rows with the change "+→NULL" are rows introduced in 2015-1)

I don't understand why some rows are yellow with ```@@ = :```

**Comment by rgrp** [comment]
@sabas wow that daff diff is really nice - i wish we could start automating that! Anyway all looks good.

Could you still give me a bit of a summary info for the merge: e.g. explain what the new data reflects e.g. if a new release tell me a bit about it.

**Comment by sabas** [comment]
It's the second release of 2015 (they release two editions per year).

This is the pdf attached to the file release containing more or less the same text of the previous releases with some statistics: 103034 entries total, with 2866 changes from 2015-1 (2187 additions).
http://www.unece.org/fileadmin/DAM/cefact/locode/2015-2_UNLOCODE_SecretariatNotes.pdf

**Pull request merged**
