### PR TITLE
Fix 2014.2 commit

### PR DESCRIPTION
**Pull request by sabas**
I realized I forgot to run the rmstr.php script on the codelist, so there were still the "headers" (detected as row which have the country but not the locatiion).
I fixed running the script and doing minor modifications.

### CODE REVIEW

**Comment by rgrp** [comment]
One comment. I'd recommend data files are all lower case with '-' for word separator (if needed). (This may be separate from this commit - but only just noticed).

**Comment by sabas** [comment]
@rgrp ah ok, I was using the lower camel case notation... Do you want me to rename the files?

**Comment by sabas** [comment]
Done, I bumped again the version.

/cc @sxren

**Comment by sabas** [comment]
Ok, I delete this thing and fork again

**Pull request closed without merging**
